config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'users#index'
  get '/login' => 'users#index', as: 'login'
  get '/register' => 'users#new', as: 'register'
  get '/profile' => 'users#show', as: 'profile' 

  post '/sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/posts' => 'posts#index', as: 'posts'

  resources :posts do 
    resources :comments
  end    


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length: {minimum: 1}

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: {minimum: 1}
  validates :email, presence: true, length: {minimum: 1}
  validates :password, presence: true, length: {minimum: 1}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private
        def comment_params
            params.require(:comment).permit(:creator, :body)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        search = params[:search]
        if search
            @posts = Array.new
            Post.all.each do |post|
                if (post.title.include? search) || (post.body.include? search) 
                    @posts.push(post)                
                elsif User.find_by(id:post.creator) && (User.find_by(id:post.creator).name.include? search)
                    @posts.push(post)                
                end
            end

        else
            @posts = Post.all.reverse
        end

        @user = User.find_by(id:session[:user_id])
    end
    
    def show 
        @post = Post.find(params[:id])
    end

    def new 
        @post = Post.new
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)

        if (@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if (@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end

    private def post_params
        params.require(:post).permit(:title, :body, :creator)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by(email:login_params[:email])
        if user && user.authenticate(login_params[:password])
            session[:user_id] = user.id
            redirect_to '/posts'
        else
            flash[:login_errors] = ['invalid credentials']
            redirect_to '/login'
        end
    end

    private 
        def login_params
            params.require(:login).permit(:email, :password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        
    end

    def create
        alia = User.find_by(email:user_params[:email])
        user = User.new(user_params)
        if User.find_by(email:user_params[:email])
            flash[:register_errors] = ['This EMAIL was already registered!']
            redirect_to '/register'
        elsif User.find_by(email:user_params[:name])
            flash[:register_errors] = ['This NAME was already registered!']
            redirect_to '/register'
        elsif user.save 
            session[:user_id] = user.id
            redirect_to '/posts'
        else
            flash[:register_errors] = user.errors.full_messages
            redirect_to '/register'
        end
    end

    def new 

    end

    def show
        @profile = User.find_by(id:params[:id])
        # @user = User.find_by(id:session[:user_id])
    end

    private 
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <div>
        <p>
            <strong>
                <% if (user = User.find_by(id:comment.creator)) %>
                    <%= link_to user.name, profile_path(id:user.id), {:class => 'text-dark'} %>
                <% else %>
                    <span class="text-dark">Unknown</span>
                <% end %>
            </strong>:
            <%= comment.body%>
        </p>

    </div>

<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.hidden_field(:creator, :value => session[:user_id]) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_field(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-outline-primary'})%>
    </p>
<% end %>

app/views/custom/_empty_navbar.html.erb
<% @user = User.find_by(id: session[:user_id]) %>

  <div class="container">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <% if @user %>
            <span class="text-muted"><%= link_to @user.name, profile_path(id:@user.id), {:class => "text-muted"} %></span>
        <% end %>
      </div>
      <div class="col-4 text-center">
        <h1><%= link_to "Blogly", '/posts', {:class => 'text-dark'}%><h1>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <%= link_to 'Log In', '/login', {:class => 'btn btn-sm btn-outline-secondary'} %>
        <%= link_to 'Sign Up', '/register', {:class => 'btn btn-sm btn-outline-secondary', :style => 'margin-left: 15px;'} %>
      </div>
    </div>
    <hr>

app/views/custom/_posts_navbar.html.erb
<% @user = User.find_by(id: session[:user_id]) %>

<div class="container">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <% if @user %>
            <span><%= link_to @user.name, profile_path(id:@user.id), {:class => "text-muted"} %></span>
        <% end %>
      </div>
      <div class="col-4 text-center">
        <h1><%= link_to "Blogly", '/posts', {:class => 'text-dark'}%><h1>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
        </a>
        <%= link_to 'Log In', '/login', {:class => 'btn btn-sm btn-outline-secondary'} %>
        <%= link_to 'Sign Up', '/register', {:class => 'btn btn-sm btn-outline-secondary', :style => 'margin-left: 15px;'} %>
      </div>
    </div>
    <hr>
    <div class="nav-scroller py-1 mb-2">
    <nav class="nav">
      <%= link_to "Home", '/posts', {:class => 'p-2 text-muted'} %>
      <%= link_to "Create Post", new_post_path, {:class => 'p-2 text-muted'} %>
    </nav>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render 'custom/posts_navbar' %>
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
   
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'} )%>
    </p>

     <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, :size => "100x4", :class => 'form-control') %><br>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>

<% end %>

app/views/posts/index.html.erb
    <%= render 'custom/posts_navbar' %>
   
    <div class="container">
    
        <h1 class="text-center"><%= link_to 'Blogly Posts', '/posts', {:class => 'text-dark'} %></h1>
        <form action="/posts" method="GET">
            <input id="search_input" type="text" placeholder="search..." name="search" class="form-control">
            <input id="search_submit" type="submit" name="submit" value="search" class="btn btn-secondary">
            <style>
                #search_input {
                    margin-right: auto;
                    margin-left: auto;
                    width: 50%;     
                    display: block;
                }

                #search_submit {
                    margin-top: 10px;
                    margin-bottom: 20px;
                    margin-right: auto;
                    margin-left: auto;
                    width: 50%;     
                    display: block;
                }
            </style>
        </form>

        <% @posts.each do |post| %> 
            <div class="card" style="margin-bottom: 30px; padding: 10px;">
                <div class="card-title">
                    <h3><%= post.title %></h3>
                </div>
                <p><%= post.body %></p>
                <% if (user = User.find_by(id:post.creator)) %>
                    <p><i>Created by: <strong><%= link_to user.name, profile_path(id:user.id), {:class => 'text-dark'} %></strong></i></p>
                <% end %>
                 <%= link_to "Read More", post_path(post), {:class => 'btn btn-outline-primary'} %>
            </div>
        <% end %>

    </div>

app/views/posts/new.html.erb
<%= render 'custom/posts_navbar' %>
<h1>Create Post</h1>

<%= form_with model: @post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %><br>
    <%= f.label :body %><br>
    <%= f.text_area(:body, :size => "100x4", :class => 'form-control') %><br>
    <%= f.hidden_field(:creator, :value => session[:user_id]) %>
    <%= f.submit({:class => 'btn btn-primary'}) %>
    <style>
        #post_body {

        }
    </style>

<% end %>

app/views/posts/show.html.erb
<%= render 'custom/posts_navbar' %>

<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<% if (user = User.find_by(id:@post.creator)) %>
    <p><i>Created by: <strong><%= link_to user.name, profile_path(id:user.id), {:class => 'text-dark'} %></strong></i></p>

    <% if @post.creator == session[:user_id] %>
        <%= link_to 'Edit', edit_post_path(@post), {:class => 'btn btn-outline-primary'} %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-outline-danger' %>
    <% end %>
<% else %>
    <%= link_to 'Edit', edit_post_path(@post), {:class => 'btn btn-outline-primary'} %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-outline-danger' %>
<% end %>

<hr>

<%= render 'comments/comments'%>
<%= render 'comments/form' %>

app/views/users/index.html.erb
    <%= render 'custom/empty_navbar' %>
    <div class="container">
        <form action="/sessions" method="POST">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <input type="hidden" name="login[email]" class="form-control" value="guest@test.com">
            <input type="hidden" name="login[password]" class="form-control" value="Guest">
            <input type="submit" name="submit" class="btn btn-outline-secondary form-control" value="Continue as a Guest" style="">
        </form>
        <br><br>

        <h1 id="Login">Login</h1>
        <form action="/sessions" method="POST">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <label>Email</label>
            <input type="email" name="login[email]" class="form-control"><br>
            <label>Password</label>
            <input type="password" name="login[password]" class="form-control"><br>
            <input type="submit" name="submit" class="submit btn btn-primary" value="Submit">
        </form>

        <div>
            <% if flash[:login_errors] %>
                <% flash[:login_errors].each do |error| %>
                    <p><%= error %></p>
                <% end %>
            <% end %>
        </div>
    </div>

app/views/users/new.html.erb
    <%= render 'custom/empty_navbar' %>
    <div class="container">
        <h1 id="Register">Register</h1>
        <form action="/users" method="POST">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <label>Name</label>
            <input type="name" name="user[name]" class="form-control"><br>
            <label>Email</label>
            <input type="email" name="user[email]" class="form-control"><br>
            <label>Password</label>
            <input type="password" name="user[password]" class="form-control"><br>
            <label>Password Confirmation</label>
            <input type="password" name="user[password_confirmation]" class="form-control"><br>
            <input type="submit" name="submit" class="submit btn btn-primary" value="Submit">
        </form>
        <div>
            <% if flash[:register_errors] %>
                <% flash[:register_errors].each do |error| %>
                    <p><%= error %></p>
                <% end %>
            <% end %>
        </div>
    </div>

app/views/users/show.html.erb
<%= render 'custom/posts_navbar' %>
    <% if @profile %>
        <p>Username: <strong><%= @profile.name %></strong></h2>
        <p>Email: <strong><%= @profile.email %></strong></p>
        <p><i>Creator id: <strong><%= @profile.id %></strong></i></p>
    <% else %>
        <p>Unknown user</p>
    <% end %>
<hr>